[package]
name = "sparrow-transforms"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = """
Implementation of transforms and pipeline for executing them.
"""

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
derive_more.workspace = true
error-stack.workspace = true
itertools.workspace = true
parking_lot.workspace = true
sparrow-arrow = { path = "../sparrow-arrow" }
sparrow-batch = { path = "../sparrow-batch" }
sparrow-expr-execution = { path = "../sparrow-expr-execution" }
sparrow-physical = { path = "../sparrow-physical" }
sparrow-scheduler = { path = "../sparrow-scheduler" }
tracing.workspace = true

[dev-dependencies]
index_vec.workspace = true
sparrow-expressions = { path = "../sparrow-expressions" }

[lib]
doctest = false
