apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kaskada-canary.fullname" . }}
  namespace: {{ include "kaskada-canary.namespaceName" . }}
  labels:
    {{- include "kaskada-canary.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kaskada-canary.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "kaskada-canary.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "kaskada-canary.s3Env" . | nindent 12 }}
            {{- include "kaskada-canary.engineLogging" . | nindent 12 }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value:  {{ $value }}
            {{- end }}
          command: ["/bin/sparrow-main", "serve"]
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 50052
          {{- with .Values.resources.engine }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: "/tmp"
              name: kaskada-canary-tmp
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_DIALECT
              value: sqlite
            - name: DB_PATH
              value: /data/kaskada.db
            - name: DB_IN_MEMORY
              value: "false"
            - name: OBJECT_STORE_BUCKET
              value: {{ .Values.storage.objectStore.bucket }}
            - name: OBJECT_STORE_PATH
              value: {{ .Values.storage.objectStore.path }}
            - name: OBJECT_STORE_TYPE 
              value: {{ .Values.storage.objectStore.type }}
            {{- include "kaskada-canary.s3Env" . | nindent 12 }}
            {{- include "kaskada-canary.managerLogging" . | nindent 12 }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value:  {{ $value }}
            {{- end }}
          command: [ "/bin/wren" ]
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 50051
            - name: rest
              protocol: TCP
              containerPort: 3365
          {{- with .Values.resources.manager }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: "/data"
              name: kaskada-canary-db
      volumes:
        - name: kaskada-canary-db
          persistentVolumeClaim:
            claimName: kaskada-canary-db
        - name: kaskada-canary-tmp
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: kaskada-canary-tmp
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.storage.tmpData.storageClassName }}
                resources:
                  requests:
                    storage: {{ .Values.storage.tmpData.storage }}
      serviceAccountName: {{ include "kaskada-canary.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
