[package]
name = "sparrow-session"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = """
The Sparrow session builder.
"""

[dependencies]
arrow-array.workspace = true
hashbrown.workspace = true
arrow-schema.workspace = true
derive_more.workspace = true
error-stack.workspace = true
futures.workspace = true
itertools.workspace = true
smallvec.workspace = true
sparrow-api = { path = "../sparrow-api" }
sparrow-compiler = { path = "../sparrow-compiler" }
sparrow-merge = { path = "../sparrow-merge" }
sparrow-runtime = { path = "../sparrow-runtime" }
sparrow-sources = { path = "../sparrow-sources" }
sparrow-syntax = { path = "../sparrow-syntax" }
sparrow-instructions = { path = "../sparrow-instructions" }
static_init.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
uuid.workspace = true

[dev-dependencies]

[lib]
bench = false
doctest = false
